using System.Text.RegularExpressions;

namespace WinFinger.Services;

/// <summary>Chinese labels for live-read menu items (verbatim port of mac ShortcutChineseTranslator).</summary>
public static class ShortcutChineseTranslator
{
    public static string GroupTitle(string title)
    {
        var normalized = Normalize(title);
        if (GroupTranslations.TryGetValue(normalized, out var translated)) return translated;
        return ContainsChinese(title) ? title : "应用";
    }

    public static string ActionTitle(string title)
    {
        if (ContainsChinese(title)) return title;

        var normalized = Normalize(title);
        if (ActionTranslations.TryGetValue(normalized, out var translated)) return translated;

        if (QuotedValue(normalized, "Run") is { } run) return $"运行“{run}”";
        if (QuotedValue(normalized, "Debug") is { } debug) return $"调试“{debug}”";
        if (QuotedValue(normalized, "Recompile") is { } recompile) return $"重新编译“{recompile}”";
        if (QuotedValue(normalized, "Rebuild Module") is { } rebuild) return $"重新构建模块“{rebuild}”";
        if (normalized.StartsWith("Hide ", StringComparison.Ordinal)) return $"隐藏 {normalized[5..]}";
        if (normalized.StartsWith("Quit ", StringComparison.Ordinal)) return $"退出 {normalized[5..]}";
        if (normalized.StartsWith("Exit ", StringComparison.Ordinal)) return $"退出 {normalized[5..]}";
        if (normalized.StartsWith("Undo ", StringComparison.Ordinal)) return "撤销上一步操作";

        // Keep the page consistently Chinese when a third-party app exposes an
        // action that is not yet in the local dictionary.
        return "应用命令";
    }

    public static string KeyName(string key) => key.ToLowerInvariant() switch
    {
        "space" => "空格",
        "tab" => "制表",
        "enter" or "return" => "回车",
        "escape" or "esc" => "退出",
        _ => key
    };

    private static string Normalize(string value) =>
        value.Replace("…", "").Replace("...", "").Trim();

    private static readonly Regex Cjk = new("[\\u4e00-\\u9fff]", RegexOptions.Compiled);

    private static bool ContainsChinese(string value) => Cjk.IsMatch(value);

    private static string? QuotedValue(string value, string prefix)
    {
        var lead = prefix + " '";
        if (!value.StartsWith(lead, StringComparison.Ordinal) || !value.EndsWith("'", StringComparison.Ordinal)) return null;
        var inner = value[lead.Length..^1];
        return inner.Length == 0 ? null : inner;
    }

    private static readonly Dictionary<string, string> GroupTranslations = new(StringComparer.Ordinal)
    {
        ["IntelliJ IDEA"] = "应用",
        ["CLion"] = "应用",
        ["WebStorm"] = "应用",
        ["Chrome"] = "应用",
        ["Safari"] = "应用",
        ["File"] = "文件",
        ["Edit"] = "编辑",
        ["View"] = "视图",
        ["Navigate"] = "导航",
        ["Code"] = "代码",
        ["Refactor"] = "重构",
        ["Build"] = "构建",
        ["Run"] = "运行",
        ["Tools"] = "工具",
        ["VCS"] = "版本控制",
        ["Git"] = "版本控制",
        ["Window"] = "窗口",
        ["Help"] = "帮助",
        ["History"] = "历史记录",
        ["Bookmarks"] = "书签",
        // Windows-only menu names
        ["Format"] = "格式",
        ["Insert"] = "插入",
        ["Selection"] = "选择",
        ["Go"] = "转到",
        ["Terminal"] = "终端",
        ["Debug"] = "调试",
        ["Home"] = "开始",
        ["Layout"] = "布局",
        ["Review"] = "审阅",
        ["Options"] = "选项",
        ["Settings"] = "设置",
        ["Search"] = "搜索",
        ["Image"] = "图像",
        ["Filter"] = "滤镜",
        ["Layer"] = "图层",
        ["Select"] = "选择",
        ["Type"] = "文字",
        ["Data"] = "数据",
        ["Formulas"] = "公式",
        ["References"] = "引用",
        ["Mailings"] = "邮件",
        ["Design"] = "设计",
        ["Transitions"] = "切换",
        ["Animations"] = "动画",
        ["Slide Show"] = "幻灯片放映",
        ["Project"] = "项目",
        ["Test"] = "测试",
        ["Analyze"] = "分析",
        ["Extensions"] = "扩展",
    };

    private static readonly Dictionary<string, string> ActionTranslations = new(StringComparer.Ordinal)
    {
        ["Settings"] = "设置",
        ["Scratch File"] = "新建临时文件",
        ["Hide Others"] = "隐藏其他应用",
        ["Show All"] = "显示全部应用",
        ["Project Structure"] = "项目结构",
        ["Save All"] = "全部保存",
        ["Reload All from Disk"] = "从磁盘重新加载全部",
        ["Undo"] = "撤销",
        ["Redo"] = "重做",
        ["Cut"] = "剪切",
        ["Copy"] = "复制",
        ["Paste"] = "粘贴",
        ["Paste from History"] = "从历史记录粘贴",
        ["Paste as Plain Text"] = "粘贴为纯文本",
        ["Delete"] = "删除",
        ["Search In Selection"] = "在选中内容中搜索",
        ["Find"] = "查找",
        ["Find Action"] = "查找操作",
        ["Replace"] = "替换",
        ["Find Next Occurrence"] = "查找下一个匹配项",
        ["Find Previous Occurrence"] = "查找上一个匹配项",
        ["Select All Occurrences"] = "选择全部匹配项",
        ["Add Selection for Next Occurrence"] = "选择下一个匹配项",
        ["Unselect Occurrence"] = "取消选择当前匹配项",
        ["Find in Files"] = "在文件中查找",
        ["Replace in Files"] = "在文件中替换",
        ["Find by XPath"] = "按 XPath 查找",
        ["Find Usages"] = "查找用法",
        ["Find Usages Settings"] = "查找用法设置",
        ["Show Usages"] = "显示用法",
        ["Find Usages in File"] = "在文件中查找用法",
        ["Highlight Usages in File"] = "高亮文件中的用法",
        ["Next Highlighted Usage"] = "下一个高亮用法",
        ["Previous Highlighted Usage"] = "上一个高亮用法",
        ["Column Selection Mode"] = "列选择模式",
        ["Select All"] = "全选",
        ["Add Carets to Ends of Selected Lines"] = "在选中行末添加光标",
        ["Extend Selection"] = "扩大选择范围",
        ["Shrink Selection"] = "缩小选择范围",
        ["Toggle Case"] = "切换大小写",
        ["Join Lines"] = "合并行",
        ["Unindent Line or Selection"] = "减少行或选中内容缩进",
        ["Toggle Bookmark"] = "切换书签",
        ["Add Mnemonic Bookmark"] = "添加助记书签",
        ["Commit"] = "提交",
        ["Project"] = "项目",
        ["Bookmarks"] = "书签",
        ["Problems"] = "问题",
        ["Structure"] = "结构",
        ["Services"] = "服务",
        ["Git"] = "版本控制",
        ["AI Assistant"] = "AI 助手",
        ["Terminal"] = "终端",
        ["Enter Full Screen"] = "进入全屏",
        ["Quick Definition"] = "快速查看定义",
        ["Quick Documentation"] = "快速文档",
        ["Parameter Info"] = "参数信息",
        ["Type Info"] = "类型信息",
        ["Context Info"] = "上下文信息",
        ["Jump to Source"] = "跳转到源码",
        ["Recent Locations"] = "最近位置",
        ["Recent Files"] = "最近文件",
        ["Recent Changes"] = "最近更改",
        ["Quick Switch Scheme"] = "快速切换方案",
        ["Increase Font Size in All Editors"] = "增大所有编辑器字体",
        ["Decrease Font Size in All Editors"] = "减小所有编辑器字体",
        ["Back"] = "后退",
        ["Forward"] = "前进",
        ["Class"] = "类",
        ["File"] = "文件",
        ["Symbol"] = "符号",
        ["Text"] = "文本",
        ["Line:Column"] = "行和列",
        ["Endpoint"] = "端点",
        ["Next Highlighted Error"] = "下一个高亮错误",
        ["Previous Highlighted Error"] = "上一个高亮错误",
        ["Last Edit Location"] = "上次编辑位置",
        ["Next Method"] = "下一个方法",
        ["Previous Method"] = "上一个方法",
        ["Move Caret to Matching Brace"] = "将光标移到匹配括号",
        ["Custom Folding"] = "自定义代码折叠",
        ["Next Change"] = "下一个更改",
        ["Previous Change"] = "上一个更改",
        ["Select In"] = "在视图中选择",
        ["Jump to Navigation Bar"] = "跳转到导航栏",
        ["Declaration or Usages"] = "声明或用法",
        ["Implementation(s)"] = "实现",
        ["Type Declaration"] = "类型声明",
        ["Super Method"] = "父类方法",
        ["Test"] = "测试",
        ["Related Symbol"] = "相关符号",
        ["File Structure"] = "文件结构",
        ["File Path"] = "文件路径",
        ["Type Hierarchy"] = "类型层次结构",
        ["Method Hierarchy"] = "方法层次结构",
        ["Call Hierarchy"] = "调用层次结构",
        ["Override Methods"] = "重写方法",
        ["Implement Methods"] = "实现方法",
        ["Generate"] = "生成",
        ["Basic"] = "基本补全",
        ["Type-Matching"] = "类型匹配补全",
        ["Complete Current Statement"] = "补全当前语句",
        ["Cyclic Expand Word"] = "循环扩展单词",
        ["Cyclic Expand Word (Backward)"] = "反向循环扩展单词",
        ["Call Inline Completion"] = "调用行内补全",
        ["Insert Inline Proposal"] = "插入行内建议",
        ["Insert Inline Proposal's Word"] = "插入行内建议的单词",
        ["Insert Inline Proposal's Line"] = "插入行内建议的整行",
        ["Run Inspection by Name"] = "按名称运行检查",
        ["Configure Current File Analysis"] = "配置当前文件分析",
        ["Insert Live Template"] = "插入实时模板",
        ["Surround With"] = "使用模板包围",
        ["Unwrap/Remove"] = "解包或移除",
        ["Expand"] = "展开",
        ["Expand Recursively"] = "递归展开",
        ["Expand All"] = "全部展开",
        ["Collapse"] = "折叠",
        ["Collapse Recursively"] = "递归折叠",
        ["Collapse All"] = "全部折叠",
        ["Fold Selection / Remove Region"] = "折叠选中内容或移除区域",
        ["Fold Code Block"] = "折叠代码块",
        ["Comment with Line Comment"] = "添加或移除行注释",
        ["Comment with Block Comment"] = "添加或移除块注释",
        ["Reformat Code"] = "重新格式化代码",
        ["Reformat File"] = "重新格式化文件",
        ["Auto-Indent Lines"] = "自动缩进行",
        ["Optimize Imports"] = "优化导入",
        ["Move Statement Down"] = "下移语句",
        ["Move Statement Up"] = "上移语句",
        ["Move Element Left"] = "左移元素",
        ["Move Element Right"] = "右移元素",
        ["Move Line Down"] = "下移行",
        ["Move Line Up"] = "上移行",
        ["Convert Java to Kotlin"] = "将 Java 转换为 Kotlin",
        ["Refactor This"] = "重构当前项",
        ["Rename"] = "重命名",
        ["Change Signature"] = "更改签名",
        ["Variable"] = "提取变量",
        ["Constant"] = "提取常量",
        ["Field"] = "提取字段",
        ["Parameter"] = "提取参数",
        ["Functional Parameter"] = "提取函数参数",
        ["Method"] = "提取方法",
        ["Move Instance Method"] = "移动实例方法",
        ["Copy Class"] = "复制类",
        ["Safe Delete"] = "安全删除",
        ["Type Migration"] = "类型迁移",
        ["Build Project"] = "构建项目",
        ["Run"] = "运行",
        ["Debug"] = "调试",
        ["Attach to Process"] = "附加到进程",
        ["Stop"] = "停止",
        ["Stop Background Processes"] = "停止后台进程",
        ["Step Over"] = "单步跳过",
        ["Force Step Over"] = "强制单步跳过",
        ["Step Into"] = "单步进入",
        ["Force Step Into"] = "强制单步进入",
        ["Smart Step Into"] = "智能单步进入",
        ["Step Out"] = "单步跳出",
        ["Run to Cursor"] = "运行到光标处",
        ["Force Run to Cursor"] = "强制运行到光标处",
        ["Resume Program"] = "继续运行程序",
        ["Evaluate Expression"] = "计算表达式",
        ["Show Execution Point"] = "显示执行位置",
        ["Line Breakpoint"] = "行断点",
        ["Temporary Line Breakpoint"] = "临时行断点",
        ["View Breakpoints"] = "查看断点",
        ["Manage Coverage Reports"] = "管理覆盖率报告",
        ["Switch Task"] = "切换任务",
        ["Open Task"] = "打开任务",
        ["Close Active Task"] = "关闭当前任务",
        ["Open in Browser"] = "在浏览器中打开",
        ["Clear Context"] = "清除上下文",
        ["Upload To"] = "上传到",
        ["Push"] = "推送",
        ["Update Project"] = "更新项目",
        ["New Branch"] = "新建分支",
        ["Rollback"] = "回滚",
        ["Show Local Changes as UML"] = "以 UML 显示本地更改",
        ["Add"] = "添加",
        ["Show Diff"] = "显示差异",
        ["VCS Operations Popup"] = "版本控制操作菜单",
        ["New Tab"] = "新建标签页",
        ["New Window"] = "新建窗口",
        ["Close Tab"] = "关闭标签页",
        ["Close Window"] = "关闭窗口",
        ["Reload"] = "重新加载",
        ["Print"] = "打印",
        ["Zoom In"] = "放大",
        ["Zoom Out"] = "缩小",
        ["Actual Size"] = "实际大小",
        ["Show Line Bookmarks"] = "显示行书签",
        ["Go to Mnemonic"] = "跳转到助记书签",
        ["Emoji & Symbols"] = "表情与符号",
        ["Next Emmet Edit Point"] = "下一个 Emmet 编辑点",
        ["Previous Emmet Edit Point"] = "上一个 Emmet 编辑点",
        ["Minimize"] = "最小化",
        ["Zoom"] = "缩放窗口",
        ["Hide Active Tool Window"] = "隐藏当前工具窗口",
        ["Hide All Windows"] = "隐藏全部窗口",
        ["Jump to Last Tool Window"] = "跳转到上一个工具窗口",
        ["Maximize Tool Window"] = "最大化工具窗口",
        ["Select Next Tab"] = "选择下一个标签页",
        ["Select Previous Tab"] = "选择上一个标签页",
        ["Show List of Tabs"] = "显示标签页列表",
        ["Close Active Tab"] = "关闭当前标签页",
        ["Go to Next Splitter"] = "转到下一个分屏",
        ["Go to Previous Splitter"] = "转到上一个分屏",
        ["Next Project Window"] = "下一个项目窗口",
        ["Previous Project Window"] = "上一个项目窗口",
        // Windows-only actions
        ["New"] = "新建",
        ["Open"] = "打开",
        ["Save"] = "保存",
        ["Save As"] = "另存为",
        ["Close"] = "关闭",
        ["Exit"] = "退出",
        ["Print Preview"] = "打印预览",
        ["Page Setup"] = "页面设置",
        ["Select all"] = "全选",
        ["Word Wrap"] = "自动换行",
        ["Font"] = "字体",
        ["Status Bar"] = "状态栏",
        ["Zoom"] = "缩放",
        ["Go To"] = "转到",
        ["Time/Date"] = "时间/日期",
        ["Replace"] = "替换",
        ["Find Next"] = "查找下一个",
        ["Find Previous"] = "查找上一个",
        ["View Help"] = "查看帮助",
        ["About"] = "关于",
        ["Refresh"] = "刷新",
        ["Properties"] = "属性",
        ["Rename"] = "重命名",
        ["Copy Path"] = "复制路径",
        ["Paste Shortcut"] = "粘贴快捷方式",
        ["Invert Selection"] = "反向选择",
        ["Select None"] = "全部不选",
        ["Full Screen"] = "全屏",
        ["Toggle Full Screen"] = "切换全屏",
        ["Options"] = "选项",
    };
}
